### ISSUE TITLE
hitting ok earily sometimes cuts off letters

### ISSUE THREAD

**Issue by mateosalta** [mateosalta/nextcloud_ogra#9]
- start typing
- hit ok
- greeted with network error page, seeing a truncated address
- go back and add extra letters, wait, then hit ok, or space/backspace at end of address...

**Comment by bhdouglass** [comment]
I believe the problem is with predictive text you can either disable it ( https://api-docs.ubports.com/sdk/apps/qml/QtQuick/TextInput.html?highlight=predictive#sdk-qtquick-textinput-inputmethodhints ) or do this hack: https://github.com/bhdouglass/dice-roller/blob/master/qml/Dialogs/CollectionNameDialog.qml#L33

**Comment by mateosalta** [comment]
ok, I hope a combination of those things worked. also i hid the error page on showing the dialog so when you do type a wrong address it won't prevent typing.
